apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 380-inbound-internet-connection
  labels:
    type: software
    platform: azure
    code: '380'
  annotations:
    displayName: Inbound Internet Connection
    description: Inbound Internet Connection
    vpn/required: false
spec:
  version: v1.0.0
  modules:
    - name: inbound-internet-connection
      alias: inbound-internet-connection
      version: v1.0.0
  variables:
    - name: inbound-internet-connection_name
      type: string
      description: The name of the resource group
    - name: region
      type: string
      description: The Azure location where the resource group will be provisioned
    - name: subscription_id
      type: string
    - name: client_id
      type: string
    - name: client_secret
      type: string
      sensitive: true
    - name: tenant_id
      type: string
